# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development:
  adapter: postgresql
  encoding: utf8
  database: db/development
  pool: 5
  username: 
  password:

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: db/test
  pool: 5
  username: 
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: db/my_database_production
  pool: 5
  username: 
  password:

cucumber:
  <<: *TEST